### ISSUE TITLE
couldnt find your email

### ISSUE THREAD

**Issue by corysimmons** [ttaubert/nss-taskcluster#2]
sorry, don't have twitter and couldn't track down any other way to contact you.

did you ever make https://timtaubert.de/blog/2016/01/build-your-own-signal-desktop/ ? Is it maintained?

**Comment by ttaubert** [comment]
You can use tim [at] timtaubert [dot] de to contact me. I have no maintained version of Signal Desktop. I build one myself using the above guide every few weeks.
